version: "3"

# MariaDB:  8988 
# MySQL:    8989
services:
    reverseproxy:
        image: nginx
        container_name: nginx
        volumes:
            - "./etc/nginx/conf.d:/etc/nginx/conf.d"
            - "./etc/letsencrypt:/etc/letsencrypt"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./etc/nginx/conf.d/default.template:/etc/nginx/conf.d/default.template"
            - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./etc/nginx/log/error.log:/var/log/nginx/error.log"
        ports:
            - "80:80"
            - "443:443"
            - "3389:3389"
            - "9595:9595"
#            - "8000:8000"
#            - "9000:9000"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        expose:
          - 9000
        ports:
          - 9000:9000
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
    web:
        image: web
        build: .
        container_name: apache
        volumes:
            - "./web:/var/www/site"
            - "./etc/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf"
            - "./etc/apache/sites-available:/etc/apache2/sites-available"
            - "./etc/apache/sites-enabled:/etc/apache2/sites-enabled"
            - "./etc/php:/etc/php"
            - "./log/apache2:/var/log/apache2"
        ports:
            - "8099:80"
        restart: always
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        restart: always
    mysqldb:
        image: mysql
        container_name: mysql
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
            - "./etc/mysql:/etc/mysql"
    memcached:
        container_name: memcached
        image: 'bitnami/memcached:latest'
        ports:
            - "11211:11211"
    pureftpd:
        container_name: ftp
        image: vipconsult/proftpd
        ports:
            - "21:21"
            - "20:20"
            - "5000-5100:5000-5100"
        volumes:
            - ./data/ftpuser:/home/ftpuser
            - ./etc/proftpd:/etc/proftpd
            - ./web:/home/ftpuser/web
        privileged: true
        restart: always
    mariadb:
        image: mariadb
        container_name: mariadb
        restart: always
        ports:
            - "8988:3306"
        env_file:
            - ".env"
        environment:
          MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
        volumes:
            - "./data/db/mariadb:/var/lib/mysql"
            - "./etc/mariadb:/etc/mysql"
    redis:
        container_name: redis
        image: 'bitnami/redis:latest'
        environment:
          - REDIS_PASSWORD=_Q9PbHvHLfVMfHXuPpmPhwmOTIaMLiUKchq4aVmpg_
        ports:
          - '6379:6379'
        volumes:
          - "./data/redis:/bitnami/redis/data"
          - "./etc/redis:/etc/redis"
    postfix:
        image: tecnativa/postfix-relay:latest
        container_name: postfix
        ports:
          - '18171:25'
        restart: always
        volumes:
         - "/etc/localtime:/etc/localtime:ro"
         - "./etc/postfix:/etc/postfix"
