version: "3"

# MariaDB:  8988
# MySQL:    8989
services:
    certbot:
        image: certbot/certbot
        container_name: certbot-docker
        volumes:
            - "./etc/letsencrypt:/etc/letsencrypt"
            - "./etc/letsencrypt-lib/:/var/lib/letsencrypt"
    reverseproxy:
        image: nginx
        container_name: nginx
        volumes:
            - "./etc/nginx/conf.d:/etc/nginx/conf.d"
            - "./etc/letsencrypt:/etc/letsencrypt"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./etc/nginx/conf.d/default.template:/etc/nginx/conf.d/default.template"
            - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./etc/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf"
            - "./etc/nginx/log/error.log:/var/log/nginx/error.log"
        ports:
            - "80:80"
            - "443:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        ports:
            - "9000"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
    web71:
        image: apache71
        container_name: apache71
        build:
            context: .
            dockerfile: ./Dockerfile71
        volumes:
            - "./web:/var/www/site"
            - "./etc/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf"
            - "./etc/apache/sites-available:/etc/apache2/sites-available"
            - "./etc/apache/sites-enabled:/etc/apache2/sites-enabled"
            - "./etc/php:/etc/php"
            - "./log/apache2:/var/log/apache2"
            - "/etc/localtime:/etc/localtime:ro"
        ports:
            - "80"
        restart: always
    web72:
        image: apache72
        container_name: apache72
        build:
            context: .
            dockerfile: ./Dockerfile72
        volumes:
            - "./web:/var/www/site"
            - "./etc/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf"
            - "./etc/apache/sites-available:/etc/apache2/sites-available"
            - "./etc/apache/sites-enabled:/etc/apache2/sites-enabled"
            - "./etc/php:/etc/php"
            - "./log/apache2:/var/log/apache2"
            - "/etc/localtime:/etc/localtime:ro"
        ports:
            - "80"
        restart: always
    web73:
        image: apache73
        container_name: apache73
        build:
            context: .
            dockerfile: ./Dockerfile73
        volumes:
            - "./web:/var/www/site"
            - "./etc/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf"
            - "./etc/apache/sites-available:/etc/apache2/sites-available"
            - "./etc/apache/sites-enabled:/etc/apache2/sites-enabled"
            - "./etc/php:/etc/php"
            - "./log/apache2:/var/log/apache2"
            - "/etc/localtime:/etc/localtime:ro"
        ports:
            - "80"
        restart: always
    web74:
        image: apache74
        container_name: apache74
        build:
            context: .
            dockerfile: ./Dockerfile74
        volumes:
            - "./web:/var/www/site"
            - "./etc/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf"
            - "./etc/apache/sites-available:/etc/apache2/sites-available"
            - "./etc/apache/sites-enabled:/etc/apache2/sites-enabled"
            - "./etc/php:/etc/php"
            - "./log/apache2:/var/log/apache2"
            - "/etc/localtime:/etc/localtime:ro"
        ports:
            - "80"
        restart: always
    web80:
        image: apache80
        container_name: apache80
        build:
            context: .
            dockerfile: ./Dockerfile80
        volumes:
            - "./web:/var/www/site"
            - "./etc/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf"
            - "./etc/apache/sites-available:/etc/apache2/sites-available"
            - "./etc/apache/sites-enabled:/etc/apache2/sites-enabled"
            - "./etc/php:/etc/php"
            - "./log/apache2:/var/log/apache2"
            - "/etc/localtime:/etc/localtime:ro"
        ports:
            - "80"
        restart: always
    pureftpd:
        container_name: ftp
        image: vipconsult/proftpd
        ports:
            - "21:21"
            - "20:20"
            - "5000-5100:5000-5100"
        volumes:
            - ./data/ftpuser:/home/ftpuser
            - ./etc/proftpd:/etc/proftpd
            - ./web:/home/ftpuser/web
        privileged: true
        restart: always
    mariadb:
        image: mariadb
        container_name: mariadb
        restart: always
        ports:
            - "3306"
        env_file:
            - ".env"
        environment:
            MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
        volumes:
            - "./data/db/mariadb:/var/lib/mysql"
            - "./etc/mariadb:/etc/mysql"
            - "./log/mariadb:/var/log/mysql"
    postfix:
        image: tecnativa/postfix-relay:latest
        container_name: postfix
        env_file:
            - ".env"
        environment:
            - MAIL_RELAY_HOST=${MAIL_RELAY_HOST}
            - MAIL_RELAY_PORT=${MAIL_RELAY_PORT}
            - MAIL_RELAY_USER=${MAIL_RELAY_USER}
            - MAIL_RELAY_PASS=${MAIL_RELAY_PASS}
        ports:
            - '25'
        restart: always
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "./etc/postfix:/etc/postfix"
