#!/bin/bash
docker run -it --rm \
-v /root/webserver/etc/letsencrypt:/etc/letsencrypt \
-v /root/webserver/var/lib/letsencrypt:/var/lib/letsencrypt \
-v /root/webserver/web:/data/letsencrypt \
-v /root/webserver/log/letsencrypt:/var/log/letsencrypt \
certbot/certbot \
renew
docker restart nginx
