#!/bin/sh
docker run -it --rm \
-v /root/workspace/etc/letsencrypt:/etc/letsencrypt \
-v /root/workspace/var/lib/letsencrypt:/var/lib/letsencrypt \
-v /root/workspace/web:/data/letsencrypt \
-v /root/workspace/log/letsencrypt:/var/log/letsencrypt \
certbot/certbot \
certonly --webroot \
--register-unsafely-without-email --agree-tos \
--webroot-path=/data/letsencrypt \
-d domain.tld \
-d www.domain.tld
